In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from dezero import Variable
import dezero.functions as F

In [3]:
x = Variable(np.random.randn(2, 3))
W = Variable(np.random.randn(3, 4))
y = F.matmul(x, W)
y.backward()

In [4]:
x.grad

variable([[-2.18748278  1.86543752 -0.81058346]
          [-2.18748278  1.86543752 -0.81058346]])

In [6]:
W.grad

variable([[ 0.84623807  0.84623807  0.84623807  0.84623807]
          [-1.91532628 -1.91532628 -1.91532628 -1.91532628]
          [ 0.82314555  0.82314555  0.82314555  0.82314555]])