In [1]:
import cupy as cp
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dropout_ratio = .6
x = cp.ones(10)

In [3]:
mask = cp.random.randn(10) > dropout_ratio

In [4]:
mask

array([ True, False, False, False,  True, False,  True,  True,  True,
       False])

In [5]:
y = x * mask

In [6]:
y

array([1., 0., 0., 0., 1., 0., 1., 1., 1., 0.])

In [7]:
mask = cp.random.rand(*x.shape) > dropout_ratio

In [8]:
mask

array([False,  True,  True, False, False, False,  True,  True,  True,
        True])

In [9]:
y = x * mask

In [10]:
y

array([0., 1., 1., 0., 0., 0., 1., 1., 1., 1.])

In [11]:
scale = 1 - dropout_ratio

In [12]:
y = x * scale

In [13]:
y

array([0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4])

In [14]:
x = cp.random.randn(5,5,3, 3)

In [15]:
x

array([[[[-0.84183759,  1.46560688, -1.26528324],
         [-1.24935961, -0.08896632, -0.7258076 ],
         [-0.53218696,  0.66569242,  1.36997668]],

        [[ 0.14084188,  0.2134449 , -0.13362108],
         [ 0.62732489, -0.22253835, -0.08320524],
         [ 0.09556475, -0.84701934,  0.13985847]],

        [[ 0.89411288, -0.41992966,  0.60913858],
         [ 0.78635364, -0.33483583,  0.64969922],
         [ 0.2305344 , -0.11186623, -1.86999182]],

        [[-1.41463974,  0.08206662,  2.01201032],
         [ 0.81562194,  0.43678297, -0.87372059],
         [ 0.39138365, -1.96413289, -0.77786643]],

        [[ 1.00772514, -1.61215465, -0.23165373],
         [ 0.60424815,  0.28387307, -1.30100089],
         [-1.63632956,  0.32554129, -2.44099378]]],


       [[[ 1.2144005 , -0.7740053 , -0.54833155],
         [-0.61941676,  0.87226773, -0.97834486],
         [-1.00919181, -1.51465415, -0.72561439]],

        [[-0.44761956, -0.86744079, -0.99816194],
         [-0.29749702,  0.38147778, 

In [16]:
k = cp.random.randn(3, 3)

In [17]:
x * k

array([[[[-0.37301949,  1.85406063,  0.68712786],
         [ 0.09703887, -0.01693495, -1.57818422],
         [ 0.75739862,  0.59281194, -3.06946191]],

        [[ 0.06240725,  0.27001769,  0.07256459],
         [-0.04872488, -0.0423607 , -0.18092012],
         [-0.13600597, -0.75428707, -0.31335588]],

        [[ 0.39618275, -0.53123048, -0.33080031],
         [-0.06107679, -0.0637368 ,  1.41269538],
         [-0.32809229, -0.09961904,  4.18975646]],

        [[-0.62682897,  0.10381808, -1.09264732],
         [-0.06335008,  0.08314268, -1.89980381],
         [-0.55700996, -1.74909824,  1.74282629]],

        [[ 0.44652451, -2.03945036,  0.12580245],
         [-0.04693249,  0.05403591, -2.82887513],
         [ 2.32879391,  0.2899008 ,  5.46909852]]],


       [[[ 0.53810267, -0.97915258,  0.29777829],
         [ 0.04811065,  0.16603824, -2.1272971 ],
         [ 1.43626309, -1.34882875,  1.62575447]],

        [[-0.19834089, -1.0973528 ,  0.5420643 ],
         [ 0.02310686,  0.0726152 , 

In [18]:
(x * k).shape

(5, 5, 3, 3)

In [19]:
y = x * k

In [20]:
y.sum(axis=(-2, -1)).shape

(5, 5)

In [21]:
import dezero.functions as F

In [22]:
x1 = cp.random.rand(1, 3, 7, 7)

In [23]:
col1 = F.im2col(x1, kernel_size=5, stride = 1, pad=0, to_matrix=True)

In [24]:
col1.shape

(9, 75)

In [25]:
x2 = cp.random.rand(10, 3, 7, 7)
col2 = F.im2col(x1, kernel_size=5, stride = 1, pad=0, to_matrix=False)

In [26]:
col2.shape

(1, 3, 5, 5, 3, 3)

In [27]:
from dezero.layers import Linear

In [28]:
l = Linear(20)

In [29]:
import numpy as np
x = np.random.randn(5, 10)

In [30]:
l(x)

variable([[ 0.30168219 -0.30935402 -1.36223449 -0.26203994 -0.77706766 -0.41336508
            0.39643466  0.25136242 -0.18603843  0.49429137  0.79419766  0.08838072
           -1.17543372  0.42403247 -0.03857414 -0.38769707 -1.24456411  0.77698657
           -0.08712113  0.24266292]
          [ 1.33686396 -1.11527788  1.05982348 -0.01594778  0.28517096 -0.52599152
           -1.64471202 -1.16631733  1.46555847  0.96895146 -0.55803385  0.26351747
           -0.29419424 -1.27132973 -1.23828044 -0.5888144   0.65172502  0.96236543
            0.58455351  0.86803533]
          [-0.86666778  1.34499533  1.68730174  0.59381831 -0.47092001 -0.70130622
           -0.67524927  2.54592396  0.74419608 -0.25553216 -1.4491918  -1.26275314
           -1.17383195 -0.05831005 -0.72213925  1.8542899  -0.53964783  0.27654812
           -0.49221409 -2.18584077]
          [ 1.00631511  0.47152903 -1.06389085 -1.01981105  0.37539852 -0.35607177
            0.87878891 -0.25633456  0.12255096  2.04050056  0.

In [32]:
l.W.shape

(10, 20)