In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline

In [3]:
x = np.array([[1,2,3], [4,5,6]])
y = x.reshape(6)

In [4]:
y

array([1, 2, 3, 4, 5, 6])

In [5]:
from dezero import Variable
import dezero.functions as F

In [6]:
x = Variable(np.array([[1,2,3], [4,5,6]]))

In [7]:
y = F.reshape(x, (6,))

In [8]:
y.shape

(6,)

In [9]:
y.backward(retain_grad=True)

In [10]:
x.grad

variable([[1 1 1]
          [1 1 1]])

In [11]:
y.grad

variable([1 1 1 1 1 1])

In [12]:
x = Variable(np.array([[1,2,3], [4,5,6]]))

In [13]:
x.reshape(3, 2)

variable([[1 2]
          [3 4]
          [5 6]])

In [14]:
x.reshape((3, 2))

variable([[1 2]
          [3 4]
          [5 6]])

In [15]:
x = np.array([[1,2,3], [4,5,6]])

In [16]:
y = x.transpose()

In [17]:
y

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
x.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
x = Variable(np.array([[1,2,3], [4,5,6]]))

In [21]:
x.transpose()

variable([[1 4]
          [2 5]
          [3 6]])

In [22]:
x.T

variable([[1 4]
          [2 5]
          [3 6]])

In [23]:
x = np.array([[1,2,3], [4,5,6]])

In [24]:
x.sum(axis=0)

array([5, 7, 9])

In [25]:
x = np.array([1,2,3])

In [26]:
y = np.broadcast_to(x, (2, 3))

In [27]:
y

array([[1, 2, 3],
       [1, 2, 3]])

In [28]:
x0 = Variable(np.array([1,2,3]))
x1 = Variable(np.array([10]))
y = x0 + x1

In [29]:
y

variable([11 12 13])

In [30]:
x0 = Variable(np.array([1,2,3]))
x1 = Variable(np.array([10]))
y = x0 + x1

In [31]:
y.backward()

In [32]:
x1.grad

variable([3])

array([3.])