In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import dezero.layers as L
import dezero.functions as F
from dezero import Layer

In [3]:
model = Layer()
model.l1 = L.Linear(5)
model.l2 = L.Linear(3)
def predict(model, x):
    y = model.l1(x)
    y = F.sigmoid(y)
    y = model.l2(y)
    return y

In [4]:
x = np.random.rand(100, 3)

In [5]:
predict(model, x)

variable([[ 1.86789404 -0.20163648  3.7606135 ]
          [ 1.80487551 -0.89941004  3.06078677]
          [ 1.87955727 -0.79618281  3.37792629]
          [ 1.97306765 -1.05078675  3.45543815]
          [ 2.052795   -0.75793227  4.557283  ]
          [ 1.69922871 -1.48565026  2.99628274]
          [ 1.65560202 -1.75948675  2.948162  ]
          [ 1.53160376 -1.84920303  2.76046181]
          [ 1.84937333 -0.35005397  2.77107879]
          [ 1.49781496 -1.19340688  2.57449425]
          [ 1.64941809 -1.38565004  2.68973269]
          [ 1.22261776 -1.53344881  2.20585737]
          [ 1.92583097 -0.28659606  3.43715239]
          [ 2.06981429 -0.65999959  4.69806383]
          [ 1.57013417 -0.61528742  2.3866645 ]
          [ 1.35812643 -1.0028745   2.26877868]
          [ 1.87537124 -0.20922037  2.7763195 ]
          [ 1.57512632 -1.59699792  2.77724541]
          [ 1.51290294 -1.27216016  2.61156496]
          [ 1.82403012 -0.34278328  3.44964702]
          [ 1.83574035 -0.7882179   3.41

In [6]:
for p in model.params():
    print(p)

variable([0. 0. 0.])
variable([[ 1.48763206 -3.22344968  3.35147448]
          [ 0.99659395  0.66277784  1.27580277]
          [-0.425202   -0.25848006  2.50694366]
          [-0.32533984 -2.00674328 -1.97279326]
          [ 2.0204538   2.41046251  1.10965581]])
variable([0. 0. 0. 0. 0.])
variable([[-0.09464091  4.3301105   1.98477191 -0.32992428 -0.18224744]
          [-0.70447934  0.75176278 -0.92415526 -1.82347759  0.09761122]
          [ 0.69819585 -1.91234117 -3.95249463 -1.78004153 -2.72424783]])


In [7]:
for p in model.l1.params():
    print(p)

variable([0. 0. 0. 0. 0.])
variable([[-0.09464091  4.3301105   1.98477191 -0.32992428 -0.18224744]
          [-0.70447934  0.75176278 -0.92415526 -1.82347759  0.09761122]
          [ 0.69819585 -1.91234117 -3.95249463 -1.78004153 -2.72424783]])


In [8]:
for p in model.l2.params():
    print(p)

variable([0. 0. 0.])
variable([[ 1.48763206 -3.22344968  3.35147448]
          [ 0.99659395  0.66277784  1.27580277]
          [-0.425202   -0.25848006  2.50694366]
          [-0.32533984 -2.00674328 -1.97279326]
          [ 2.0204538   2.41046251  1.10965581]])


In [9]:
class TwoLayerNet(Layer):
    def __init__(self, hidden_size, out_size):
        super().__init__()
        self.l1 = L.Linear(hidden_size)
        self.l2 = L.Linear(out_size)

    def forward(self, x):
        y = F.sigmoid(self.l1(x))
        y = self.l2(y)
        return y

In [13]:
tl = TwoLayerNet(100, 3)

In [16]:
tl(x).shape

(100, 3)